quality_string: best[subtitle]/best
discord_presence: true
fzf:
    executable: fzf
    opts: []
    state: true
schedule:
    site_url: https://graphql.anilist.co/ # DO NOT CHANGE UNLESS YOU KNOW WHAT YOU'RE DOING
    date_format: "%b. %d, %A"
    time_format: "%X"
ffmpeg:
    executable: ffmpeg
    hls_download: false
    submerge: true
