game:
  exe: /home/oiviadesu/Games/genshin-impact/drive_c/Program Files/Genshin Impact/Genshin
    Impact Game/launcher.bat
  working_dir: /home/oiviadesu/Games/genshin-impact/drive_c/Program Files/Genshin
    Impact/Genshin Impact Game
system: {}
wine:
  battleye: false
  eac: false
  esync: true
  fsr: false
  fsync: true
  version: lutris-GE-Proton8-5-x86_64
