game:
  exe: honkers-railway-launcher
game_slug: honkai-star-rail
linux: {}
name: 'Honkai: Star Rail'
requires: null
script:
  files:
  - engine: https://github.com/an-anime-team/the-honkers-railway-launcher/releases/download/1.1.0/honkers-railway-launcher
  game:
    exe: honkers-railway-launcher
  installer:
  - chmodx: engine
  - merge:
      dst: $GAMEDIR
      src: engine
  - execute:
      command: cd "$GAMEDIR"; mkdir "honkers-railway-launcher-files"; cd "/home/$USER/.local/share";
        ln -sf "$GAMEDIR/honkers-railway-launcher-files" "honkers-railway-launcher";
slug: honkai-star-rail-hrl
system:
  prime: false
variables: {}
version: HRL
year: 2023
