game:
  arch: win64
  exe: drive_c/osu/osu!.exe
  prefix: /home/oiviadesu/Games/osu
  working_dir: /home/oiviadesu/Games/osu/drive_c/osu
game_slug: osu
name: osu!
requires: null
script:
  files:
  - installer: https://m1.ppy.sh/r/osu!install.exe
  game:
    exe: drive_c/osu/osu!.exe
    prefix: $GAMEDIR
  installer:
  - task:
      arch: win64
      install_gecko: 'False'
      install_mono: 'False'
      prefix: /home/oiviadesu/Games/osu
      wine_path: /home/oiviadesu/.local/share/lutris/runners/wine/lutris-osu-2-x86_64/bin/wine
  - task:
      arch: win64
      key: HelBuflen
      path: HKEY_CURRENT_USER\Software\Wine\DirectSound
      prefix: /home/oiviadesu/Games/osu
      value: '512'
      wine_path: /home/oiviadesu/.local/share/lutris/runners/wine/lutris-osu-2-x86_64/bin/wine
  - merge:
      dst: $GAMEDIR/drive_c/osu/
      src: installer
  - task:
      app: dotnet48
      arch: win64
      prefix: /home/oiviadesu/Games/osu
      wine_path: /home/oiviadesu/.local/share/lutris/runners/wine/lutris-osu-2-x86_64/bin/wine
  - task:
      app: gdiplus
      arch: win64
      prefix: /home/oiviadesu/Games/osu
      wine_path: /home/oiviadesu/.local/share/lutris/runners/wine/lutris-osu-2-x86_64/bin/wine
  - task:
      app: corefonts vlgothic meiryo cjkfonts
      arch: win64
      prefix: /home/oiviadesu/Games/osu
      wine_path: /home/oiviadesu/.local/share/lutris/runners/wine/lutris-osu-2-x86_64/bin/wine
  - task:
      arch: win64
      env:
        PULSE_LATENCY_MSEC: '30'
      exclude_processes: osu!install.exe
      executable: /home/oiviadesu/Games/osu/drive_c/osu/osu!install.exe
      include_processes: osu!.exe
      prefix: /home/oiviadesu/Games/osu
      wine_path: /home/oiviadesu/.local/share/lutris/runners/wine/lutris-osu-2-x86_64/bin/wine
  - task:
      app: win10
      arch: win64
      prefix: /home/oiviadesu/Games/osu
      wine_path: /home/oiviadesu/.local/share/lutris/runners/wine/lutris-osu-2-x86_64/bin/wine
  - task:
      arch: win64
      prefix: /home/oiviadesu/Games/osu
      wine_path: /home/oiviadesu/.local/share/lutris/runners/wine/lutris-osu-2-x86_64/bin/wine
  system:
    env:
      PULSE_LATENCY_MSEC: 30
  wine:
    dxvk: true
    esync: true
    version: lutris-osu-2-x86_64
slug: osu-stable
system:
  dri_prime: false
  env:
    PULSE_LATENCY_MSEC: '30'
  limit_cpu_count: '4'
  mangohud: false
  single_cpu: false
  vk_icd: ''
variables: {}
version: Stable
wine:
  Audio: auto
  Desktop: false
  MouseWarpOverride: force
  WineDesktop: 1920x1080
  battleye: false
  dxvk: true
  dxvk_nvapi: false
  dxvk_version: v1.10.3
  eac: false
  esync: true
  fsr: false
  fsync: true
  system_winetricks: false
  version: lutris-osu-2-x86_64
year: 2007
